# site settings
title: Dhruval Javia
subtitle:
email: dhruvaljavia@gmail.com
description: "An Ingenious Mechanical Engineer <br /> <br /> Enthusiastic about solving global climate and energy problems through innovation and sustainability-driven outlook"
baseurl: /dhruvaljavia.github.io # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Stanford
state: CA
zip_code: 94305
country: United States
phone: +1 (650) 509-2107

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/dhruvaljavia
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/dhruval_javia?igsh=NTc4MTIwNjQ2YQ==
  LinkedIn: https://www.linkedin.com/in/dhruvaljavia
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
